#!/bin/bash
# 04-network.sh -- Host network config (Linux Bridge + OVS)
# Target: Debian 13 / Native ifupdown (No Netplan)
#
# Logic:
# - Native Linux Bridges for physical ports and DMZ (Simple & Stable)
# - Open vSwitch for internal trunking (VLAN 20/30) only

set -euo pipefail

# -- Validation ----------------------------------------------------------------
for VAR in SITE_NAME IF_LAN IF_ISP IF_MGMT_ACCESS IF_ISP_REAL IP_BR_EXT GW_BR_EXT; do
    if [[ -z "${!VAR:-}" ]]; then
        echo "ERROR: missing variable: ${VAR}"
        exit 1
    fi
done

echo "=== [04-network] Start (Hybrid Bridge/OVS) ==="

# Extract IP and Netmask
IP_ADDR=$(echo "${IP_BR_EXT}" | cut -d/ -f1)
NETMASK="255.255.255.0"

# -- Cleanup OVS ---------------------------------------------------------------
# Ensure no old OVS bridges conflict with Linux Bridges
echo "--- Cleaning old OVS bridges ---"
for br in br-ext br-isp br-isp-real br-dmz br-mgmt-access; do
    ovs-vsctl del-br "$br" 2>/dev/null || true
done

# -- Generate /etc/network/interfaces ------------------------------------------
echo "--- Generating /etc/network/interfaces ---"

cat <<EOF > /etc/network/interfaces
# Generated by 04-network.sh
auto lo
iface lo inet loopback

# --- NATIVE LINUX BRIDGES ---

# Bridge LAN (Host Management + Default Route)
auto br-ext
iface br-ext inet static
    address ${IP_ADDR}
    netmask ${NETMASK}
    gateway ${GW_BR_EXT}
    dns-nameservers 8.8.8.8 8.8.4.4
    bridge_ports ${IF_LAN}
    bridge_stp off
    bridge_fd 0

# Bridge ISP Simulated (vmnet3)
auto br-isp
iface br-isp inet manual
    bridge_ports ${IF_ISP}
    bridge_stp off
    bridge_fd 0

# Bridge ISP Real (Physical Port)
auto br-isp-real
iface br-isp-real inet manual
    bridge_ports ${IF_ISP_REAL}
    bridge_stp off
    bridge_fd 0

# Bridge Management Access (Jump Host)
auto br-mgmt-access
iface br-mgmt-access inet manual
    bridge_ports ${IF_MGMT_ACCESS}
    bridge_stp off
    bridge_fd 0

# Bridge DMZ Virtual (Bastion <-> Router00)
auto br-dmz
iface br-dmz inet manual
    bridge_ports none
    bridge_stp off
    bridge_fd 0

# --- OPEN VSWITCH (Internal VLAN Trunk) ---

auto ovs-lab
allow-ovs ovs-lab
iface ovs-lab inet manual
    ovs_type OVSBridge
EOF

echo "--- Config written. Applying changes ---"

# -- Application ---------------------------------------------------------------
# Install bridge-utils if missing (required for native bridges)
if ! command -v brctl >/dev/null; then
    apt-get update && apt-get install -y bridge-utils
fi

# Transition: Flush physical IP and bring up bridges
# We use a subshell to minimize SSH downtime
echo "--- Reconfiguring interfaces (SSH might flicker) ---"
bash -c "
    ifdown ${IF_LAN} --force || true
    ip addr flush dev ${IF_LAN} || true
    systemctl restart networking
    ifup br-ext --force || true
    ifup ovs-lab --force || true
"
# Desactiver le passage du trafic bridge dans iptables (Gain de performance CPU)
cat <<EOF | sudo tee /etc/sysctl.d/99-bridge-performance.conf
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
EOF

sudo modprobe br_netfilter
# Ajouter le module au chargement automatique
echo "br_netfilter" | sudo tee /etc/modules-load.d/br_netfilter.conf

# Charger les parametres immediatement
sudo sysctl -p /etc/sysctl.d/99-bridge-performance.conf

# -- Verification --------------------------------------------------------------
echo ""
echo "=== Checks ==="
echo "--- Linux Bridges ---"
brctl show
echo "--- Open vSwitch ---"
ovs-vsctl show
echo "--- Host IP ---"
ip -4 addr show br-ext | grep inet || echo "ERROR: br-ext has no IP"

echo ""
echo "=== [04-network] Ready ==="