#!/bin/bash
# 04-network.sh -- Host network config (Hybrid Linux Bridge + OVS)
set -euo pipefail

# -- Validation ----------------------------------------------------------------
# Mise à jour des variables pour inclure LAN5 (UGREEN) et LAN10 (Physique)
for VAR in SITE_NAME IF_LAN10 IF_LAN5 MAC_OF_IF_LAN5 IF_ISP IP_BR_EXT GW_BR_EXT; do
    if [[ -z "${!VAR:-}" ]]; then
        echo "ERROR: missing variable: ${VAR}"
        exit 1
    fi
done

echo "=== [04-network] Start (Hybrid Bridge/OVS) ==="

# Extract IP and Netmask
IP_ADDR=$(echo "${IP_BR_EXT}" | cut -d/ -f1)
NETMASK="255.255.255.0"

# -- Cleanup OVS ---------------------------------------------------------------
echo "--- Cleaning old OVS bridges ---"
for br in br-ext10 br-ext5 br-isp br-dmz; do
    ovs-vsctl del-br "$br" 2>/dev/null || true
done

# -- Generate /etc/network/interfaces ------------------------------------------
echo "--- Generating /etc/network/interfaces ---"

cat <<EOF > /etc/network/interfaces
# Generated by 04-network.sh
auto lo
iface lo inet loopback

# --- NATIVE LINUX BRIDGES ---

# Bridge LAN10 (Host Management + Default Route - RJ45 Droite)
auto br-ext10
iface br-ext10 inet static
    address ${IP_ADDR}
    netmask ${NETMASK}
    gateway ${GW_BR_EXT}
    dns-nameservers 8.8.8.8 8.8.4.4
    bridge_ports ${IF_LAN10}
    bridge_stp off
    bridge_fd 0

# Force bridge creation at boot even if the physical dongle is missing.
# This ensures Libvirt/KVM can always attach the VM's virtual interface.
auto br-ext5
iface br-ext5 inet manual
    pre-up /bin/true
    bridge_ports ${IF_LAN5}
    bridge_stp off
    bridge_fd 0
    bridge_hw ${MAC_OF_IF_LAN5}

# Enable hotplug support for the USB Ethernet dongle.
# Allows the system to dynamically bind the device to the bridge when plugged in.
allow-hotplug ${IF_LAN5}
iface ${IF_LAN5} inet manual

# Bridge ISP (Internet - RJ45 Gauche)
auto br-isp
iface br-isp inet manual
    bridge_ports ${IF_ISP}
    bridge_stp off
    bridge_fd 0

# Bridge DMZ Virtual (Bastion <-> Router00)
auto br-dmz
iface br-dmz inet manual
    bridge_ports none
    bridge_stp off
    bridge_fd 0

# --- OPEN VSWITCH (Internal VLAN Trunk) ---
auto ovs-lab
allow-ovs ovs-lab
iface ovs-lab inet manual
    ovs_type OVSBridge

# Inclusion du Wi-Fi (Site A/B management)
source /etc/network/interfaces.d/*
EOF

echo "--- Config written. Applying changes ---"

# -- Application ---------------------------------------------------------------
if ! command -v brctl >/dev/null; then
    sudo apt-get update && sudo apt-get install -y bridge-utils
fi

# Transition : On évite 'systemctl restart networking' pour ne pas couper le WiFi
echo "--- Bringing up bridges (Selective ifup) ---"
sudo modprobe br_netfilter
echo "br_netfilter" | sudo tee /etc/modules-load.d/br_netfilter.conf

# Désactiver le passage du trafic bridge dans iptables pour la performance
cat <<EOF | sudo tee /etc/sysctl.d/99-bridge-performance.conf
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
EOF
sudo sysctl -p /etc/sysctl.d/99-bridge-performance.conf

# Montage manuel des interfaces pour garder le Wi-Fi actif
sudo ifup br-ext10
sudo ifup br-isp
sudo ifup br-dmz
sudo ifup ovs-lab
# LAN5 ne monte que si le dongle est là
sudo ifup br-ext5 || echo "Warning: br-ext5 (UGREEN) not connected"

# -- Verification --------------------------------------------------------------
echo ""
echo "=== Checks ==="
brctl show
echo "--- Host IP ---"
ip -4 addr show br-ext10 | grep inet || echo "ERROR: br-ext10 has no IP"
echo "=== [04-network] Ready ==="
