#!/bin/bash
# 17-install-k3s.sh -- Install k3s on all nodes (server + agents)
#
# Run from m-server00 (site A) AFTER:
#   - All k3s VMs are up and cloud-init complete on both sites
#     (created by 16-create-debian-13-vms.sh with --extra-pubkey INTRA_LAB_PUBLIC_KEY)
#   - DNS/DHCP reservations pushed to both routers (09-create-router00.sh)
#   - All VM names resolve (ping m-k3s-server, ping c-k3s-agent-1)
#
# Uses the shared SSH key generated by 16-create-k3s-vms.sh (/etc/k3s-ssh/k3s-nodes)
# -- no agent forwarding needed, no sudo SSH issues.
#
# Usage:
#   source site-A.env && source site-A-secrets.env
#   bash 17-install-k3s.sh
#   (no sudo needed -- SSH as lab with NOPASSWD sudo on remotes)
#
# Required env vars (from site-A.env):
#   SITE_LETTER  PRIMARY_DOMAIN

set -euo pipefail

for VAR in SITE_LETTER PRIMARY_DOMAIN INTRA_LAB_PRIVATE_KEY; do
    if [[ -z "${!VAR:-}" ]]; then
        echo "ERROR: missing variable: ${VAR}"
        echo "       source site-A.env && source site-A-secrets.env && bash $0"
        exit 1
    fi
done

if [[ "${SITE_LETTER}" != "m" ]]; then
    echo "ERROR: run this script from site A (maison) only -- SITE_LETTER=${SITE_LETTER}"
    exit 1
fi

# ------------------------------------------------------------------------------
# Configuration -- edit here to add/remove nodes
# ------------------------------------------------------------------------------

K3S_SERVER="m-k3s-server"      # control plane hostname (DNS must resolve)

# Agents: "hostname:site_letter"
# site_letter used to find the k3s SSH key on the right host
K3S_AGENTS=(
    "m-k3s-agent-1:m"
    "m-k3s-agent-2:m"
    "c-k3s-agent-1:c"
    "c-k3s-agent-2:c"
)

K3S_VERSION="stable"           # or pin: "v1.32.4+k3s1"
K3S_SSH_KEY="${HOME}/.ssh/k3s-nodes"   # lab home -- no sudo needed, always accessible

# k3s server flags
# --flannel-iface : use the primary interface (auto-detected, not hardcoded eth0
#                   since Debian 13 uses predictable names like enp1s0)
# --disable servicelb     : use NodePort instead of built-in LB
# --tls-san               : allow kubectl from anywhere that resolves the name
K3S_SERVER_EXTRA_ARGS=(
    "--disable servicelb"
    "--tls-san ${K3S_SERVER}"
    "--tls-san ${K3S_SERVER}.${PRIMARY_DOMAIN}"
)

# k3s agent flags
K3S_AGENT_EXTRA_ARGS=(
)

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

SSH_OPTS="-i ${K3S_SSH_KEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"

ssh_run() {
    local HOST="$1"; shift
    ssh ${SSH_OPTS} "lab@${HOST}" "$@"
}

ssh_sudo() {
    local HOST="$1"; shift
    ssh ${SSH_OPTS} "lab@${HOST}" "sudo $*"
}

wait_for_ssh() {
    local HOST="$1"
    echo -n "    Waiting for SSH on ${HOST}"
    for i in $(seq 1 60); do
        if ssh ${SSH_OPTS} -o ConnectTimeout=3 "lab@${HOST}" true 2>/dev/null; then
            echo " OK"
            return 0
        fi
        echo -n "."
        sleep 5
    done
    echo ""
    echo "ERROR: ${HOST} not reachable after 5 min -- is cloud-init done?"
    echo "       Check: virsh console <vm-name>"
    return 1
}

resolve_ip() {
    local HOST="$1"
    # Try to resolve via getent (uses system DNS -- your lab dnsmasq)
    getent hosts "${HOST}" 2>/dev/null | awk '{print $1}' | head -1
}

# ------------------------------------------------------------------------------
# Checks
# ------------------------------------------------------------------------------

echo "=== [17-install-k3s] Start ==="
echo "    Server  : ${K3S_SERVER}"
echo "    Agents  : ${K3S_AGENTS[*]}"
echo "    k3s     : ${K3S_VERSION}"
echo "    SSH key : ${K3S_SSH_KEY}"
echo ""

if [[ ! -f "${K3S_SSH_KEY}" ]]; then
    echo "    ${K3S_SSH_KEY} not found -- writing from INTRA_LAB_PRIVATE_KEY"
    mkdir -p "$(dirname ${K3S_SSH_KEY})"
    echo "${INTRA_LAB_PRIVATE_KEY}" | base64 -d > "${K3S_SSH_KEY}"
    chmod 600 "${K3S_SSH_KEY}"
    echo "    Written: ${K3S_SSH_KEY}"
else
    echo "    Using existing: ${K3S_SSH_KEY}"
fi

# ------------------------------------------------------------------------------
# 1. Verify DNS resolves + SSH reachable for all nodes
# ------------------------------------------------------------------------------
echo "==> [1] Verify connectivity to all nodes"

wait_for_ssh "${K3S_SERVER}"

for AGENT_SPEC in "${K3S_AGENTS[@]}"; do
    AGENT_HOST="${AGENT_SPEC%%:*}"
    wait_for_ssh "${AGENT_HOST}"
done

# Resolve server IP for agent join URL
K3S_SERVER_IP=$(resolve_ip "${K3S_SERVER}")
if [[ -z "${K3S_SERVER_IP}" ]]; then
    echo "ERROR: cannot resolve ${K3S_SERVER} -- check DNS"
    exit 1
fi
echo "    ${K3S_SERVER} resolved to ${K3S_SERVER_IP}"

# ------------------------------------------------------------------------------
# 2. Install k3s server (control plane)
# ------------------------------------------------------------------------------
echo ""
echo "==> [2] Install k3s server on ${K3S_SERVER} (${K3S_SERVER_IP})"

# Install k3s-specific prerequisites not in the base cloud-init
ssh_run "${K3S_SERVER}" "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq open-iscsi nfs-common 2>/dev/null || true"

SERVER_IP_ON_NODE=$(ssh_run "${K3S_SERVER}" "hostname -I | awk '{print \$1}'")
# Detect the primary interface (Debian 13 uses enp1s0, not eth0)
SERVER_IFACE=$(ssh_run "${K3S_SERVER}" "ip route get 8.8.8.8 | awk '/dev/{print \$5}' | head -1")
echo "    Node self-IP : ${SERVER_IP_ON_NODE}"
echo "    Node iface   : ${SERVER_IFACE}"

EXTRA_ARGS="${K3S_SERVER_EXTRA_ARGS[*]} --node-ip ${SERVER_IP_ON_NODE} --advertise-address ${SERVER_IP_ON_NODE} --tls-san ${SERVER_IP_ON_NODE} --flannel-iface ${SERVER_IFACE}"

ssh_run "${K3S_SERVER}" "curl -sfL https://get.k3s.io | \
    INSTALL_K3S_CHANNEL=${K3S_VERSION} \
    sudo sh -s - server ${EXTRA_ARGS}"

echo "    k3s server installed"

# Wait for control plane to be ready
echo -n "    Waiting for control plane"
for i in $(seq 1 36); do
    if ssh_sudo "${K3S_SERVER}" "kubectl get nodes --no-headers 2>/dev/null" | grep -q "Ready"; then
        echo " -- Ready"
        break
    fi
    echo -n "."
    sleep 5
    [[ $i -eq 36 ]] && echo "" && echo "ERROR: control plane not ready after 3 min" && exit 1
done

# ------------------------------------------------------------------------------
# 3. Retrieve node token
# ------------------------------------------------------------------------------
echo ""
echo "==> [3] Retrieve node token"

K3S_TOKEN=$(ssh_sudo "${K3S_SERVER}" "cat /var/lib/rancher/k3s/server/node-token")
echo "    Token: ${K3S_TOKEN:0:20}... (${#K3S_TOKEN} chars)"

# ------------------------------------------------------------------------------
# 4. Install k3s agents
# ------------------------------------------------------------------------------
echo ""
echo "==> [4] Install k3s agents"

for AGENT_SPEC in "${K3S_AGENTS[@]}"; do
    AGENT_HOST="${AGENT_SPEC%%:*}"
    echo ""
    echo "    --> ${AGENT_HOST}"

    # k3s-specific prerequisites
    ssh_run "${AGENT_HOST}" "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq open-iscsi nfs-common 2>/dev/null || true"

    AGENT_IP=$(ssh_run "${AGENT_HOST}" "hostname -I | awk '{print \$1}'")
    AGENT_IFACE=$(ssh_run "${AGENT_HOST}" "ip route get 8.8.8.8 | awk '/dev/{print \$5}' | head -1")
    echo "    Node self-IP : ${AGENT_IP}"
    echo "    Node iface   : ${AGENT_IFACE}"

    AGENT_ARGS="--node-ip ${AGENT_IP} --flannel-iface ${AGENT_IFACE}"

    # Write token to a temp file on the agent to avoid shell quoting/expansion issues
    echo "${K3S_TOKEN}" | ssh_run "${AGENT_HOST}" "sudo tee /tmp/k3s-token > /dev/null"

    # Verify token file was written
    TOKEN_CHECK=$(ssh_run "${AGENT_HOST}" "sudo wc -c < /tmp/k3s-token 2>/dev/null || echo 0")
    if [[ "${TOKEN_CHECK}" -lt 10 ]]; then
        echo "    ERROR: token file empty on ${AGENT_HOST} -- aborting"
        exit 1
    fi
    echo "    Token file: ${TOKEN_CHECK} bytes on ${AGENT_HOST}"

    # Pre-write the k3s agent env file with the token before running the installer.
    # The installer will find the env file and use it directly.
    ssh_run "${AGENT_HOST}" "
        sudo mkdir -p /etc/systemd/system
        sudo tee /etc/systemd/system/k3s-agent.service.env > /dev/null << 'ENVEOF'
K3S_URL=https://${K3S_SERVER_IP}:6443
ENVEOF
        sudo sh -c 'echo K3S_TOKEN=\$(cat /tmp/k3s-token) >> /etc/systemd/system/k3s-agent.service.env'
        sudo cat /etc/systemd/system/k3s-agent.service.env
    "

    ssh_run "${AGENT_HOST}" "
        curl -sfL https://get.k3s.io | \
            INSTALL_K3S_CHANNEL=${K3S_VERSION} \
            K3S_URL=https://${K3S_SERVER_IP}:6443 \
            K3S_TOKEN_FILE=/tmp/k3s-token \
            sudo -E sh -s - agent ${AGENT_ARGS}
        sudo rm -f /tmp/k3s-token
    "

    echo "    ${AGENT_HOST}: agent installed"
done

# ------------------------------------------------------------------------------
# 5. Wait for all nodes Ready
# ------------------------------------------------------------------------------
echo ""
echo "==> [5] Wait for all nodes Ready"

EXPECTED=$((1 + ${#K3S_AGENTS[@]}))
echo -n "    Waiting for ${EXPECTED} nodes"

for i in $(seq 1 60); do
    READY=$(ssh_sudo "${K3S_SERVER}" \
        "kubectl get nodes --no-headers 2>/dev/null | grep -c ' Ready'" || echo 0)
    if [[ "${READY}" -ge "${EXPECTED}" ]]; then
        echo " -- ${READY}/${EXPECTED} Ready"
        break
    fi
    echo -n "."
    sleep 5
    [[ $i -eq 60 ]] && echo "" && \
        echo "WARN: only ${READY}/${EXPECTED} Ready after 5 min -- check: kubectl get nodes"
done

echo ""
ssh_sudo "${K3S_SERVER}" "kubectl get nodes -o wide"

# ------------------------------------------------------------------------------
# 6. Fetch and patch kubeconfig
# ------------------------------------------------------------------------------
echo ""
echo "==> [6] Fetch kubeconfig"

KUBECONFIG_RAW=$(ssh_sudo "${K3S_SERVER}" "cat /etc/rancher/k3s/k3s.yaml")

# Use Python for reliable YAML patching
KUBECONFIG_PATCHED=$(echo "${KUBECONFIG_RAW}" | python3 -c "
import sys, re
text = sys.stdin.read()
text = text.replace('https://127.0.0.1:6443', 'https://${K3S_SERVER_IP}:6443')
text = text.replace('https://localhost:6443',  'https://${K3S_SERVER_IP}:6443')
# Replace 'default' with context-aware values using line-anchored regex
# cluster/context names -> homelab
text = re.sub(r'(?m)^([ -]* *name: )default$',      r'\1homelab',       text)
text = re.sub(r'(?m)^( *cluster: )default$',         r'\1homelab',       text)
text = re.sub(r'(?m)^(current-context: )default$',   r'\1homelab',       text)
# user references -> homelab-admin (must come after name replacements)
text = re.sub(r'(?m)^( *user: )default$',            r'\1homelab-admin', text)
# user list entry name: the '- name: default' under 'users:' section
# We identify it by replacing any remaining '- name: default'
text = re.sub(r'(?m)^(- name: )homelab$',            r'\1homelab-admin', text)
print(text, end='')
")

mkdir -p "${HOME}/.kube"
echo "${KUBECONFIG_PATCHED}" > "${HOME}/.kube/config"
chmod 600 "${HOME}/.kube/config"

# Also write to scripts dir for easy scp to Mac
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "${KUBECONFIG_PATCHED}" > "${SCRIPT_DIR}/k3s-homelab.yaml"
chmod 600 "${SCRIPT_DIR}/k3s-homelab.yaml"

echo "    Saved: ${HOME}/.kube/config"
echo "    Saved: ${SCRIPT_DIR}/k3s-homelab.yaml"

# Quick test
echo ""
echo "    kubectl version:"
KUBECONFIG="${HOME}/.kube/config" kubectl version --short 2>/dev/null || \
    KUBECONFIG="${HOME}/.kube/config" kubectl version 2>/dev/null | head -5

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------
echo ""
echo "================================================================"
echo "  [17-install-k3s] Complete"
echo ""
echo "  Cluster : homelab"
echo "  Server  : ${K3S_SERVER} (${K3S_SERVER_IP}:6443)"
echo "  Agents  :"
for AGENT_SPEC in "${K3S_AGENTS[@]}"; do
    echo "    ${AGENT_SPEC%%:*}"
done
echo ""
echo "  On m-server00:"
echo "    kubectl get nodes"
echo "    kubectl get pods -A"
echo ""
echo "  On your Mac:"
echo "    scp lab@m-server00:scripts/k3s-homelab.yaml ~/.kube/homelab.yaml"
echo "    export KUBECONFIG=~/.kube/homelab.yaml"
echo "    kubectl get nodes"
echo ""
echo "  Or merge with existing ~/.kube/config:"
echo "    KUBECONFIG=~/.kube/config:~/.kube/homelab.yaml \\"
echo "      kubectl config view --flatten > /tmp/merged.yaml"
echo "    mv /tmp/merged.yaml ~/.kube/config"
echo "    kubectl config use-context homelab"
echo "================================================================"
